# Generated by Django 4.2.3 on 2023-07-19 02:21

from django.db import migrations, models
import django.db.models.aggregates
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('amount_of_categories', models.IntegerField(verbose_name=django.db.models.aggregates.Count('category_name'))),
            ],
        ),
        migrations.CreateModel(
            name='ProductCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Please Enter A Name', max_length=100)),
                ('description', models.TextField(default='Please Enter A Description', max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_category', models.ForeignKey(default='None Given', on_delete=django.db.models.deletion.CASCADE, to='products.categories')),
            ],
        ),
    ]
