# Generated by Django 4.2.3 on 2023-07-19 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_categories_options_alter_productcreate_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCreate',
            new_name='Product',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products'},
        ),
    ]
