# Generated by Django 4.2.3 on 2023-08-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='id_hidden',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
