# Generated by Django 4.2.3 on 2023-08-01 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_orderitem_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orderitemtracker',
            name='customer',
        ),
    ]
