# Generated by Django 4.2.3 on 2023-08-02 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_orderitem_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemtracker',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
