# Generated by Django 4.2.3 on 2023-08-02 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_orderitemtracker_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
    ]
