# Generated by Django 4.2.3 on 2023-08-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='useless',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
