# Generated by Django 4.2.3 on 2023-08-03 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_orderitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemtracker',
            name='filter_item',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
