# Generated by Django 4.2.3 on 2023-08-03 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_orderitemtracker_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemtracker',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.orderitem'),
        ),
    ]
