# Generated by Django 4.2.3 on 2023-08-03 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_orderitemtracker_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='tracker',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.orderitemtracker'),
        ),
    ]
