# Generated by Django 4.2.3 on 2023-08-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_orderitem_tracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemtracker',
            name='useless',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
