# Generated by Django 4.2.3 on 2023-08-03 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_remove_orderitemtracker_useless_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='tracker',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.orderitemtracker'),
        ),
    ]
