# Generated by Django 4.2.3 on 2023-08-03 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_orderitem_tracker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='tracker',
        ),
    ]
