# Generated by Django 4.2.3 on 2023-08-04 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_order_orderitemtracker_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitemtracker',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='store.orderitemtracker'),
        ),
    ]
