# Generated by Django 4.2.3 on 2023-08-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_order_date_ordered_orderitem_added_to_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='complete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
