# Generated by Django 4.2.3 on 2023-08-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_orderitem_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='filter_item',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
