# Generated by Django 4.2.3 on 2023-08-04 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_orderitem_filter_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='complete',
        ),
    ]
