# Generated by Django 4.2.3 on 2023-08-05 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_order_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='complete',
            field=models.BooleanField(blank=True, choices=[(True, 'Complete'), (False, 'Incomplete')], default=False, null=True),
        ),
    ]
