# Generated by Django 4.2.3 on 2023-08-12 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_delete_customerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='notes',
        ),
    ]
