# Generated by Django 4.2.3 on 2023-08-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, default='images/default/default.jpg', null=True, upload_to='images/'),
        ),
    ]
