# Generated by Django 4.2.3 on 2023-08-11 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Title for Email', max_length=150, null=True)),
                ('current', models.BooleanField(blank=True, default=False, null=True)),
                ('subject', models.CharField(blank=True, default='Store Subject', max_length=150, null=True)),
                ('body', models.TextField(blank=True, default='Body message', max_length='600', null=True)),
                ('message_sender', models.EmailField(default='mystore@example.net', max_length=254, null=True)),
                ('message_recipients', models.TextField(default='testuser@example.net', max_length=300, null=True)),
            ],
        ),
    ]
