# Generated by Django 4.2.3 on 2023-08-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='current',
        ),
        migrations.AddField(
            model_name='email',
            name='status',
            field=models.BooleanField(blank=True, choices=[(True, 'Active'), (False, 'Unactive')], default=False, null=True),
        ),
    ]
