# Generated by Django 4.2.3 on 2023-08-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_alter_email_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='status',
            field=models.BooleanField(blank=True, choices=[(True, 'Active'), (False, 'Inactive')], default=False, null=True, unique=True),
        ),
    ]
